name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
      - 'hotfix-*'

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }} (${{ matrix.composer-options }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
        os:
          - ubuntu-latest
          - macOS-latest
        composer-options:
          - ""
          - "--prefer-lowest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pcntl, posix, intl
          coverage: xdebug
          ini-values: error_reporting=E_ALL

      - name: Install dependencies
        run: composer update
          --prefer-dist
          --no-progress
          ${{ matrix.composer-options }}

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v2.0.0
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional  

      - name: Run acceptance tests
        run: composer test-acceptance

      - name: Run api tests
        run: composer test-api

      - name: Run unit tests
        run: composer test-unit

      - name: Run manual tests
        run: composer test-manual
