name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install
        run: composer install
      - name: Test
        run: composer test || true
      - name: Print files
        run: ls -al tests/_output/allure-results
